# Generated by Django 3.1.2 on 2020-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptiveLearning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userName',
            new_name='username',
        ),
    ]
