# Generated by Django 3.1.2 on 2020-10-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptiveLearning', '0002_auto_20201015_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
            ],
        ),
    ]
